snakemake_min_version: "7.30.1"
mambaforge_version: "24.7.1-0"

simulate_threads: 10
sim_clone_list: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
sim_cell_list: [500, 1000, 2000, 4000, 8000]

# BENCHMARK
benchmark_clone_list: [2, 4, 6, 8, 10]
benchmark_cells: 100
sim_types: ["targeted", "wgs"]
experiments: ["bulk", "sc"]